name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_ID: 'realcoderzdemo' 
  REGION: 'us-central1'
  SERVICE: 'my-cloud-run'
  # Format: region-docker.pkg.dev/project-id/repository-name/image-name
  IMAGE_NAME: 'gcr.io/realcoderzdemo/demo-myapp/my-app'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA_CREDS }}'

      # 1. Setup gcloud CLI to use Docker with Artifact Registry
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Authorize Docker'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # 2. Build and Push Docker Image
      - name: 'Build and Push Container'
        run: |-
          docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      # 3. Deploy to Cloud Run using the Image
      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          flags: '--allow-unauthenticated'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
